# Site settings
title: Shakti Rajpurohit
shortTitle: SR
tagline: "Hi, I'm Shakti. This site is a Work in progress."
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's
baseUrl: "/"

# Contact
phone: "" # This is my real number. You should text me.
email: "" # This is my real email address. Please don't email me.

# Internal nav
nav:
  - Projects: "/projects/"

social:
  - Facebook: "www.facebook.com"
  - LinkedIn: "www.linkedin.com"

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
